const experiences = [
 {id:1,title:'Sunrise Trek to Kalsubai',cat:'Adventure',tag:'BESTSELLER',place:'Kalsubai · 2h 45m away',desc:'Chase dawn above the clouds at Maharashtra’s highest peak.',price:1499,rating:'4.9',img:'assets/cinematic-western-ghats-trekking-young-p-2.jpg',level:'Moderate'},
 {id:2,title:'Clay & Chai: Pottery Social',cat:'Creative',tag:'NEW',place:'Koregaon Park · Pune',desc:'Shape some clay, sip masala chai, and meet good people.',price:899,rating:'4.8',img:'assets/pune-pottery-workshop-young-adults-moder-1.jpg',level:'Beginner'},
 {id:3,title:'Midnight City Cycling',cat:'Culture',tag:'NIGHT OUT',place:'Camp · Pune',desc:'See the city after dark on a guided two-wheel adventure.',price:699,rating:'4.9',img:'assets/night-cycling-city-young-people-india-ci-2.jpg',level:'Easy'},
 {id:4,title:'Lakeside Camping Escape',cat:'Chill',tag:'WEEKEND PICK',place:'Bhandardara · 3h away',desc:'Campfires, constellations, and a morning beside the lake.',price:2299,rating:'4.7',img:'assets/cinematic-western-ghats-trekking-young-p-3.jpg',level:'Easy'},
 {id:5,title:'Street Photography Walk',cat:'Culture',tag:'SMALL GROUP',place:'Old Pune · 15 min away',desc:'Find light, colour, and stories hidden in everyday streets.',price:799,rating:'4.8',img:'assets/night-cycling-city-young-people-india-ci-1.jpg',level:'Beginner'},
 {id:6,title:'Secret Sahyadri Trail',cat:'Adventure',tag:'LIMITED',place:'Tamhini · 2h away',desc:'A monsoon-green route with hidden falls and wild views.',price:1799,rating:'4.9',img:'assets/cinematic-western-ghats-trekking-young-p-1.jpg',level:'Moderate'}
];
const testimonials=[
 {q:'I booked the Kalsubai trek on a Thursday night and watched the sunrise from the summit two days later. Zero planning stress. Pure magic.',name:'Aanya Mehta',role:'Product designer · Pune',initial:'A'},
 {q:'The pottery social was warm, relaxed, and genuinely fun. I went alone and left with a lopsided mug and four new friends.',name:'Kabir Shah',role:'Student · Mumbai',initial:'K'},
 {q:'Veyra has completely changed how our group plans weekends. Pick, book, show up—and somehow every trip feels special.',name:'Rohan & friends',role:'Weekend regulars · Pune',initial:'R'}
];
let activeFilter='all',currentTestimonial=0,booking={step:1,experience:null,date:'',name:'',email:'',guests:1};
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
function renderExperiences(){
 const query=$('#searchInput').value.toLowerCase(); const vibe=$('#vibeSelect').value;
 const list=experiences.filter(x=>(activeFilter==='all'||x.cat===activeFilter)&&(vibe==='all'||x.cat===vibe)&&(x.title.toLowerCase().includes(query)||x.desc.toLowerCase().includes(query)||x.place.toLowerCase().includes(query)));
 $('#experienceGrid').innerHTML=list.map(x=>`<article class="experience-card reveal visible"><div class="card-image"><img src="${x.img}" alt="${x.title}"><span class="card-tag">${x.tag}</span><button class="heart" data-heart aria-label="Save ${x.title}">♡</button></div><div class="card-body"><div class="card-meta">${x.place.toUpperCase()} · ★ ${x.rating}</div><h3>${x.title}</h3><p>${x.desc}</p><div class="card-foot"><span class="price"><strong>₹${x.price.toLocaleString('en-IN')}</strong> <small>/ person</small></span><button class="book-link" data-book="${x.id}">BOOK NOW →</button></div></div></article>`).join('');
 $('.empty-state').hidden=!!list.length;
}
renderExperiences();
$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderExperiences()});
$('#searchForm').onsubmit=e=>{e.preventDefault();activeFilter='all';$$('.chip').forEach((x,i)=>x.classList.toggle('active',i===0));renderExperiences();$('#experiences').scrollIntoView()};
$('#experienceGrid').onclick=e=>{const book=e.target.closest('[data-book]');if(book)openBooking(+book.dataset.book);const heart=e.target.closest('[data-heart]');if(heart){heart.classList.toggle('saved');heart.textContent=heart.classList.contains('saved')?'♥':'♡';toast(heart.classList.contains('saved')?'Saved to your favourites':'Removed from favourites')}};
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeModals(){$$('.modal').forEach(m=>{m.classList.remove('open');m.setAttribute('aria-hidden','true')});document.body.style.overflow=''}
$$('[data-close]').forEach(x=>x.onclick=closeModals);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModals();$('#lightbox').classList.remove('open')}});
function openBooking(id=1){booking={step:1,experience:experiences.find(x=>x.id===id)||experiences[0],date:'',name:'',email:'',guests:1};renderBooking();openModal('#bookingModal')}
function renderBooking(){
 const c=$('#bookingContent'),x=booking.experience;$$('.booking-progress span').forEach((s,i)=>s.classList.toggle('active',i<booking.step));
 if(booking.step===1)c.innerHTML=`<div class="eyebrow">STEP 1 OF 4</div><h2>Choose an experience</h2><p>Your story starts with a good pick.</p><div class="option-list">${experiences.map(e=>`<button class="option ${e.id===x.id?'selected':''}" data-select-exp="${e.id}"><span><b>${e.title}</b><br><small>${e.place}</small></span><strong>₹${e.price.toLocaleString('en-IN')}</strong></button>`).join('')}</div><div class="booking-actions"><span></span><button class="btn" data-next>Choose date →</button></div>`;
 if(booking.step===2)c.innerHTML=`<div class="eyebrow">STEP 2 OF 4</div><h2>When are you free?</h2><p>Pick a date for <b>${x.title}</b>.</p><div class="field-grid"><label>Experience date<input id="bookDate" type="date" min="${new Date().toISOString().split('T')[0]}" value="${booking.date}" required></label><label>Number of guests<input id="bookGuests" type="number" min="1" max="12" value="${booking.guests}"></label></div><div class="booking-actions"><button class="text-link" data-back>← Back</button><button class="btn" data-next>Enter details →</button></div>`;
 if(booking.step===3)c.innerHTML=`<div class="eyebrow">STEP 3 OF 4</div><h2>Who’s exploring?</h2><p>We’ll send booking details to this email.</p><div class="field-grid"><label>Full name<input id="bookName" value="${booking.name}" placeholder="Your name"></label><label>Email address<input id="bookEmail" type="email" value="${booking.email}" placeholder="you@example.com"></label><label>Phone<input id="bookPhone" type="tel" placeholder="+91 98765 43210"></label><label>City<input value="Pune"></label></div><div class="booking-actions"><button class="text-link" data-back>← Back</button><button class="btn" data-next>Review booking →</button></div>`;
 if(booking.step===4)c.innerHTML=`<div class="eyebrow">STEP 4 OF 4</div><h2>Looks like a great plan.</h2><p>Review your weekend before confirming.</p><div class="confirm-card"><h3>${x.title}</h3><p><span>Date</span><b>${new Date(booking.date+'T12:00:00').toLocaleDateString('en-IN',{dateStyle:'long'})}</b></p><p><span>Guests</span><b>${booking.guests}</b></p><p><span>Explorer</span><b>${booking.name}</b></p><p><span>Total</span><b>₹${(x.price*booking.guests).toLocaleString('en-IN')}</b></p></div><div class="booking-actions"><button class="text-link" data-back>← Back</button><button class="btn" data-confirm>Confirm booking ✦</button></div>`;
}
$('#bookingContent').onclick=e=>{const sel=e.target.closest('[data-select-exp]');if(sel){booking.experience=experiences.find(x=>x.id===+sel.dataset.selectExp);renderBooking()}if(e.target.closest('[data-back]')){booking.step--;renderBooking()}if(e.target.closest('[data-next]')){if(booking.step===2){booking.date=$('#bookDate').value;booking.guests=+$('#bookGuests').value;if(!booking.date)return toast('Please choose a date')}if(booking.step===3){booking.name=$('#bookName').value.trim();booking.email=$('#bookEmail').value.trim();if(!booking.name||!booking.email.includes('@'))return toast('Please enter your name and email')}booking.step++;renderBooking()}if(e.target.closest('[data-confirm]')){closeModals();toast('Booking confirmed! Check your inbox ✦')}};
$$('[data-plan]').forEach(x=>x.onclick=()=>openBooking(1));$$('[data-open-auth]').forEach(x=>x.onclick=()=>openModal('#authModal'));
$$('[data-auth]').forEach(b=>b.onclick=()=>{$$('[data-auth]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#authForm .btn').textContent=b.dataset.auth==='login'?'Log in →':'Create account →'});
$('#authForm').onsubmit=e=>{e.preventDefault();$('#authForm .form-message').textContent='Success! Welcome to Veyra.';setTimeout(()=>{closeModals();toast('You’re signed in ✦')},700)};
function renderTestimonial(){const t=testimonials[currentTestimonial];$('#testimonialContent').innerHTML=`<article class="testimonial"><q>“${t.q}”</q><div class="testimonial-person"><div class="avatar">${t.initial}</div><div><strong>${t.name}</strong><small>${t.role}</small></div></div></article>`;$('#testimonialDots').innerHTML=testimonials.map((_,i)=>`<button class="${i===currentTestimonial?'active':''}" data-dot="${i}" aria-label="View testimonial ${i+1}"></button>`).join('')}
renderTestimonial();$('.testimonial-stage .next').onclick=()=>{currentTestimonial=(currentTestimonial+1)%testimonials.length;renderTestimonial()};$('.testimonial-stage .prev').onclick=()=>{currentTestimonial=(currentTestimonial-1+testimonials.length)%testimonials.length;renderTestimonial()};$('#testimonialDots').onclick=e=>{if(e.target.dataset.dot!==undefined){currentTestimonial=+e.target.dataset.dot;renderTestimonial()}};
$$('.gallery-item').forEach(x=>x.onclick=()=>{$('#lightbox img').src=x.dataset.img;$('#lightbox').classList.add('open')});$('[data-lightbox-close]').onclick=()=>$('#lightbox').classList.remove('open');
$('#newsletterForm').onsubmit=e=>{e.preventDefault();e.currentTarget.querySelector('.form-message').textContent='You’re in! Your next adventure is on its way ✦';e.currentTarget.reset()};
$('.theme-toggle').onclick=()=>{const html=document.documentElement;html.dataset.theme=html.dataset.theme==='dark'?'light':'dark';$('.theme-icon').textContent=html.dataset.theme==='dark'?'☀':'☾'};$('.menu-btn').onclick=()=>$('#navLinks').classList.toggle('open');$$('.nav-links a').forEach(a=>a.onclick=()=>$('#navLinks').classList.remove('open'));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(x=>observer.observe(x));
window.addEventListener('scroll',()=>{const bg=$('.hero-bg');if(bg)bg.style.transform=`scale(1.05) translateY(${scrollY*.09}px)`},{passive:true});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
